### ISSUE TITLE
Move repo to bevry organisation

### ISSUE THREAD

**Issue by balupton** [bevry/static-site-generator-comparison#205]
Hi @jaspervdj

Can we move this repo to the Bevry organisation? I can get extra collaborators going and make sure the the Webhook URL for regenerating the website is always up to date (it is now out of date as the website hosting has changed).

I've invited you as a member of the Bevry org, so you should be able to accept that invite, then if you want transfer the repo across yourself via the repo settings.

Let me know your thoughts and if you have any questions.

**Comment by jaspervdj** [comment]
Sounds good to me @balupton. Should we also up a redirect in the README.md then?

**Comment by balupton** [comment]
sure

**Comment by balupton** [comment]
@jaspervdj looks like you are a team member of bevry now, so you should be able to transfer the repo across via the repo settings page

**Comment by jaspervdj** [comment]
@balupton done, and yeah the redirect works fine indeed.
